services:
  master:
    build: .
    container_name: redis_master
    command: ["./app"]
    ports:
      - "6379:6379"

  slave1:
    build: .
    container_name: redis_slave1
    command: ["./app", "--port", "6380", "--replicaof", "master 6379"]
    depends_on:
      - master
    ports:
      - "6380:6380"

  slave2:
    build: .
    container_name: redis_slave2
    command: ["./app", "--port", "6381", "--replicaof", "master 6379"]
    depends_on:
      - master
    ports:
      - "6381:6381"
